apiVersion: v1
kind: Pod
metadata:
  name: s3-test
spec:
  serviceAccountName: aws-test # Your IRSA-enabled ServiceAccount
  containers:
    - name: awscli
      image: amazonlinux:2
      command: ["/bin/sh", "-c"]
      args:
        - |
          yum install -y aws-cli && \
          aws sts get-caller-identity && \
          aws s3 ls
      env:
        - name: AWS_REGION
          value: "us-west-2" # Replace with your actual cluster region if different
      tty: true
