---
apiVersion: v1
kind: Service
metadata:
  name: sample-counter-service
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  #   prometheus.io/port: "80"
spec:
  type: LoadBalancer
  selector:
    app: sample-counter
  ports:
  - protocol: TCP
    port: 80         # service port exposed to cluster/load balancer
    targetPort: 8000 # container port your app listens on
