apiVersion: v1
kind: Pod
metadata:
  name: s3-test
spec:
  serviceAccountName: aws-test  # Your IRSA-enabled SA
  containers:
    - name: awscli
      image: amazonlinux:2
      command: ["/bin/sh", "-c"]
      args:
        - |
          yum install -y aws-cli && \
          aws sts get-caller-identity && \
          aws s3 ls
      env:
        - name: AWS_REGION
          value: us-west-2  # or your cluster region
      tty: true
